### ISSUE TITLE
Packagist: This package is abandoned

### ISSUE THREAD

**Issue by ebuzzz** [websightnl/gearman#1]
The packagist page at https://packagist.org/packages/sinergi/gearman currently states that the package is abandoned. Is this on purpose, or is this due to the change in owner name?

**Comment by ebuzzz** [comment]
Thanks for changing the composer.json, but Packagist still reports "This package is abandoned and no longer maintained. No replacement package was suggested.". Is this something you can fix?

If the package is really abandonded, I wouldn't mind taking over the package, because we use it quite a lot in our company.

**Comment by gabrielbull** [comment]
@eborned Hi Eric, I am the developer behind this package. I have indeed abandoned development. I will gladly pass on the package to you. Do you have a packagist account?

**Comment by ebuzzz** [comment]
Yes, I do. Username is eborned. We use a different package prefix (websightnl/package).

**Comment by gabrielbull** [comment]
Done transferring. Here is the packagist link: https://packagist.org/packages/sinergi/gearman

**Comment by ebuzzz** [comment]
Thanks, I'll keep the old name as abandoned and redirect to a new package under the new name. That way, existing users know that someting has changed.

**Comment by gabrielbull** [comment]
Sounds good 👍🏼

**Comment by ebuzzz** [comment]
Migration has been completed. Travis is building succesfully. Thanks!
